### ISSUE TITLE
Set text string with multiple lines

### ISSUE THREAD

**Issue by marcoscgdev** [testica/codeeditor#7]
I'm trying to set a text string with some lines using "/n"

`line one\nline two`

But the editor shows "\n" instead of generating a new line.

Thanks in advance.

<img src="https://user-images.githubusercontent.com/14148259/56021130-fac75600-5d08-11e9-981c-47b1841a0d18.png" width="350">

**Comment by marcoscgdev** [comment]
I was using "/n" instead of "\n" :dizzy_face:

Thanks for this awesome library!

**Comment by testica** [comment]
@marcoscgdev I'm glad to hear that. Thank you.
